### PR TITLE
When the mvn command fails for example due to lack of space, make sure the whole build fails.

### PR DESCRIPTION
**Pull request by adelton**
This comes from https://github.com/red-hat-data-services/trustyai-explainability/pull/6.

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/trustyai-explainability/trustyai-explainability/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `FAI-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.3.x] FAI-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by ruivieira — APPROVED** [review]
LGTM, thanks @adelton

**Comment by adelton** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/trustyai-explainability_trustyai-explainability/421/pull-ci-trustyai-explainability-trustyai-explainability-main-trustyai-explainability-e2e/1718960834354352128 says

>  level=error msg=Cluster operator kube-controller-manager Degraded is True with MissingStaticPodController_SyncError::StaticPods_Error: MissingStaticPodControllerDegraded: static pod lifecycle failure - static pod: "kube-controller-manager" in namespace: "openshift-kube-controller-manager" for revision: 6 on node: "ci-op-4vmzgst0-ebf06-96xtm-master-0" didn't show up, waited: 3m0s 

which I don't think is something that this PR has caused.

**Comment by RobGeada** [comment]
Yup @adelton, that's just an instability in the test plaform, I'll retrigger it.

**Pull request merged**
