### PR TITLE
Enhancement: Add 404 response message

### PR DESCRIPTION
**Pull request by RobGeada**
Adds the following response to all TrustyAI 404s:

`Error: The queried endpoint "\example\endpoint" does not exist within TrustyAI.`

This will help distinguish between basic connectivity issues and actual malformed/mistyped endpoints. 

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/trustyai-explainability/trustyai-explainability/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `FAI-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.3.x] FAI-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by ruivieira — COMMENTED** [review]
@RobGeada LGTM

Is it possible to run a test with a profile that disables an existing endpoint (e.g. /lime or /shap) and verify it 404s?

**Review by ruivieira — APPROVED** [review]

**Comment by ruivieira** [comment]
It also seems we have to enable (or change the expectation) on a few unit tests which are failing:

```
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointMemoryTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/dir/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointPVCTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/dir/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointHibernateTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointMemoryTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointPVCTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/identity/IdentityEndpointTest.java:266 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/identity/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/GroupStatisticalParityDifferenceEndpointTest.java:138 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
```

**Review by ruivieira — CHANGES_REQUESTED** [review]
It seems like this is making some unit tests fail, too
```
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointMemoryTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/dir/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointPVCTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/dir/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointHibernateTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointMemoryTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointPVCTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/identity/IdentityEndpointTest.java:266 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/identity/request" does not exist within TrustyAI.
explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/GroupStatisticalParityDifferenceEndpointTest.java:138 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
```

**Comment by RobGeada** [comment]
> It seems like this is making some unit tests fail, too
> 
> ```
> explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointMemoryTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/dir/request" does not exist within TrustyAI.
> explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/DisparateImpactRatioEndpointPVCTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/dir/request" does not exist within TrustyAI.
> explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointHibernateTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
> explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointMemoryTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
> explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/fairness/group/GroupStatisticalParityDifferenceEndpointPVCTest.java:1 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
> explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/identity/IdentityEndpointTest.java:266 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/identity/request" does not exist within TrustyAI.
> explainability-service/src/test/java/org/kie/trustyai/service/scenarios/nodata/GroupStatisticalParityDifferenceEndpointTest.java:138 | 1 expectation failed. Response body doesn't match expectation. Expected: is ""   Actual: 404 Not Found: The queried endpoint "/metrics/group/fairness/spd/request" does not exist within TrustyAI.
> ```

Ah, it looks more like I need to go add an error message to those endpoint responses

**Review by ruivieira — APPROVED** [review]

**Pull request merged**
