### PR TITLE
Fix floating-point edge case in payload conversion

### LINKED ISSUE #210: Sending floats in metric request can cause validation errors
When sending a float where the JSON representation is missing the decimal part (e.g. `1.0` sent as `1`), the request validation fails.

### PR DESCRIPTION
**Pull request by ruivieira**
- Change `JSONNode` to `ValueNode` in order to use floating point checks
- Added type checker unit tests

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
LGTM 👍

**Comment by RobGeada** [comment]
test comment

**Review by tteofili — APPROVED** [review]
LGTM

**Comment by RobGeada** [comment]
hey tide retrigger plz

**Pull request merged**
